import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

import "primereact/resources/themes/viva-dark/theme.css";     
import "primereact/resources/primereact.min.css";
import "primeicons/primeicons.css"; 

import { Button } from 'primereact/button';
import { Steps } from 'primereact/steps';
import { useState } from 'react';
import { MenuItem, MenuItemCommandEvent } from 'primereact/menuitem';
import { Card } from 'primereact/card';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [activeIndex, setActiveIndex] = useState(1);
    // const toast = useRef(null);
    const items: MenuItem[] = [
        {
            label: 'Info',
            command: (event: MenuItemCommandEvent) => {
                // toast.current.show({ severity: 'info', summary: 'First Step', detail: event.item.label });
            }
        },
        {
            label: 'Holdings',
            command: (event: MenuItemCommandEvent) => {
                // toast.current.show({ severity: 'info', summary: 'Third Step', detail: event.item.label });
            }
        },
        {
          label: 'Overview',
          command: (event: MenuItemCommandEvent) => {
              // toast.current.show({ severity: 'info', summary: 'Third Step', detail: event.item.label });
          }
        },
        {
            label: 'Feedback',
            command: (event: MenuItemCommandEvent) => {
                // toast.current.show({ severity: 'info', summary: 'Last Step', detail: event.item.label });
            }
        }
    ];

  const portfolioCriteria = [
    "diversified",
    "too risky",
    "cost efficient",
  ]

  return (
    <>
      <Head>
        <title></title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>PortfolioBot</h1>
      <main className={styles.main}>
        <div className={styles.description}>
          <h1>Is your portfolio <span className='emphasized'>diversified</span>?</h1>

          <br></br>

          <p className='homepage-secondary-header'>Get <span className='emphasized'>AI-driven</span> feedback on your investment portfolio in minutes</p>
          
          <br></br>
          <br></br>

          <div>
            <Steps model={items} activeIndex={activeIndex} onSelect={(e) => setActiveIndex(e.index)} readOnly={false} />
          </div>
          <br></br>
          {
            activeIndex === 0 && (
              <Card>
              <p className="m-0">
                  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore sed consequuntur error repudiandae 
                  numquam deserunt quisquam repellat libero asperiores earum nam nobis, culpa ratione quam perferendis esse, cupiditate neque quas!
              </p>
            </Card>
           )
          }
          {
            activeIndex === 1 && (
              <Card>
              <p className="m-0">
                holdings
              </p>
            </Card>
           )
          }
          <br></br>
          {
            activeIndex > 0 && (
              <Button label="Back" onClick={() => setActiveIndex(activeIndex - 1)} />
            )
          }
          &nbsp;
          <Button label="Next" onClick={() => setActiveIndex(activeIndex + 1)} />
        </div>
      </main>
    </>
  )
}
